#page title
page_title                                : WiFi小秘书                      # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : #                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : #                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://static-wifi.pogou.net/apk/wifiSecretary_toutiao_1.0.5.apk                                         # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : WiFi小秘书                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : 免费                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : 随时随地，免费上网。

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : 安吉元气网络科技有限公司                                
your_link                                 :                  
your_city                                 :                                 
email_address                             : ajgenki@qq.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : 随时随地上网
    description                           : 自动连接全国上亿免费WiFi热点，走到哪连到哪，不用密码，太方便了
    fontawesome_icon_name                 : magic
    
  - title                                 : 网络质量增强
    description                           : 实时检测当时网络延迟情况，深度优化上网环境，解决卡顿问题
    fontawesome_icon_name                 : mobile

  - title                                 : 网络安全监测
    description                           : 实时监测WiFi安全、主动防御风险WiFi，推送可靠安全WiFi，防钓鱼、虚假WiFi通通不用怕
    fontawesome_icon_name                 : star

  # - title                                 : Automatic Icon and Metadata
  #   description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
  #   fontawesome_icon_name                 : sync

  # - title                                 : Easy to Tweak
  #   description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : adjust
  
  # - title                                 : Feature List
  #   description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : star

  # - title                                 : Smart App Banner
  #   description                           : Display a smart app banner on iOS devices.
  #   fontawesome_icon_name                 : arrow-alt-circle-down

  # - title                                 : Social Links
  #   description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : link

  # - title                                 : FontAwesome Support
  #   description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : info-circle

  # - title                                 : # New Feature Title
  #   description                           : # New Feature Description
  #   fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : # assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#F8F8F8"

link_color                                : "#1d63ea"

app_title_color                           : "#333333"
app_price_color                           : "#999999"
app_description_color                     : "#666666"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
theme: jekyll-theme-minimal